version: '3'

services:
  #database
  db:
    image: mysql:8
    volumes:  
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpnet
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart : always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - wpnet
  #wordpress
  wordpress:
    depends_on:
      - db
      - newrelicdaemon
    build:
      context: newrelicagent   
      args:
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_HOST: db:3306
    ports:
      - '8084:80'
    restart: always
    volumes: ['~/wordpress/html:/var/www/html']
    networks:
      - wpnet
  newrelicdaemon:
     image: newrelic/php-daemon
     networks:
       - wpnet
networks:
  wpnet:
volumes:
  db_data: {}
   
