version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - <my volume here>
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: <my db root password>
       MYSQL_DATABASE: <my db name>
       MYSQL_USER: <my db user>
       MYSQL_PASSWORD: <my db password>

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - "8001:80" #map of the ports 
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: <my db root password>


   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80" #mapping of the ports
     restart: always
     volumes: [<my volume here>]
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: <my db user>
       WORDPRESS_DB_PASSWORD: <my db password>
       WORDPRESS_DB_NAME: <my db name>
   newrelicagent:
     depends_on:
       - newrelicdaemon
     build:
       context: newrelicagent
       args:
          NEW_RELIC_AGENT_VERSION: "9.9.0.260"
          NEW_RELIC_LICENSE_KEY: <valid license key>
          NEW_RELIC_APPNAME: "New Relic wordpress checker"
          NEW_RELIC_DAEMON_ADDRESS: "newrelicdaemon:31339"
   newrelicdaemon:
     image: newrelic/php-daemon

volumes:
    db_data: {}
